== 各シート共通の変換ルール

[[building-type]]
=== 建物用途と室用途

建物用途と室用途は、以下の表の通り変換する。

[options="header",format=csv]
|===
BuildingType (XML),RoomType (XML),建物用途 (CSV),室用途 (CSV),室用途 (CSV、略称)
Office,OfficeRoom,事務所等,事務室,
Office,ComputerRoom,事務所等,電子計算機器事務室,電算事務室
Office,MeetingRoom,事務所等,会議室,
Office,TeaRoom,事務所等,喫茶室,
Office,Canteen,事務所等,社員食堂,
Office,CentralMonitoringRoom,事務所等,中央監視室,
Office,LockerRoom,事務所等,更衣室又は倉庫,更衣室・倉庫
Office,Corridor,事務所等,廊下,
Office,Lobby,事務所等,ロビー,
Office,Toilet,事務所等,便所,
Office,SmokingRoom,事務所等,喫煙室,
Office,Kitchen,事務所等,厨房,
Office,IndoorParking,事務所等,屋内駐車場,
Office,MechanicalRoom,事務所等,機械室,
Office,ElectricalRoom,事務所等,電気室,
Office,Kitchenette,事務所等,湯沸室等,
Office,StorageRoom,事務所等,食品庫等,
Office,CopyRoom,事務所等,印刷室等,
Office,GarbageStorage,事務所等,廃棄物保管場所等,ゴミ置場等
Hotel,GuestRoom,ホテル等,客室,
Hotel,BathroomInGuestRoom,ホテル等,客室内の浴室等,客室内浴室等
Hotel,FrontDesk_AllDay,ホテル等,終日利用されるフロント,フロント(終日)
Hotel,OfficeRoom_AllDay,ホテル等,終日利用される事務室,事務室(終日)
Hotel,Corridor_AllDay,ホテル等,終日利用される廊下,廊下(終日)
Hotel,Lobby_AllDay,ホテル等,終日利用されるロビー,ロビー(終日)
Hotel,Toilet_AllDay,ホテル等,終日利用される共用部の便所,便所(終日)
Hotel,SmokingRoom_AllDay,ホテル等,終日利用される喫煙室,喫煙室(終日)
Hotel,BanquetHall,ホテル等,宴会場,
Hotel,ConferenceRoom,ホテル等,会議室,
Hotel,WeddingHall,ホテル等,結婚式場,
Hotel,Restaurant,ホテル等,レストラン,
Hotel,Lounge,ホテル等,ラウンジ,
Hotel,Bar,ホテル等,バー,
Hotel,Shop,ホテル等,店舗,
Hotel,Canteen,ホテル等,社員食堂,
Hotel,LockerRoom,ホテル等,更衣室又は倉庫,更衣室・倉庫
Hotel,FrontDesk_Daytime,ホテル等,日中のみ利用されるフロント,フロント(日中)
Hotel,OfficeRoom_Daytime,ホテル等,日中のみ利用される事務室,事務室(日中)
Hotel,Corridor_Daytime,ホテル等,日中のみ利用される廊下,廊下(日中)
Hotel,Lobby_Daytime,ホテル等,日中のみ利用されるロビー,ロビー(日中)
Hotel,Toilet_Daytime,ホテル等,日中のみ利用される共用部の便所,便所(日中)
Hotel,SmokingRoom_Daytime,ホテル等,日中のみ利用される喫煙室,喫煙室(日中)
Hotel,Kitchen,ホテル等,厨房,
Hotel,IndoorParking,ホテル等,屋内駐車場,
Hotel,MechanicalRoom,ホテル等,機械室,
Hotel,ElectricalRoom,ホテル等,電気室,
Hotel,Kitchenette,ホテル等,湯沸室等,
Hotel,StorageRoom,ホテル等,食品庫等,
Hotel,CopyRoom,ホテル等,印刷室等,
Hotel,GarbageStorage,ホテル等,廃棄物保管場所等,ゴミ置場等
Hospital,Ward,病院等,病室,
Hospital,Bathroom,病院等,浴室等,
Hospital,StaffStation,病院等,看護職員室,
Hospital,Corridor_AllDay,病院等,終日利用される廊下,廊下(終日)
Hospital,Lobby_AllDay,病院等,終日利用されるロビー,ロビー(終日)
Hospital,Toilet_AllDay,病院等,終日利用される共用部の便所,便所(終日)
Hospital,SmokingRoom_AllDay,病院等,終日利用される喫煙室,喫煙室(終日)
Hospital,ConsultingRoom,病院等,診察室,
Hospital,WaitingLounge,病院等,待合室,
Hospital,OperatingRoom,病院等,手術室,
Hospital,ExaminingRoom,病院等,検査室,
Hospital,IntensiveCareUnit,病院等,集中治療室,
Hospital,DissectingRoom,病院等,解剖室等,
Hospital,Restaurant,病院等,レストラン,
Hospital,OfficeRoom,病院等,事務室,
Hospital,LockerRoom,病院等,更衣室又は倉庫,更衣室・倉庫
Hospital,Corridor_Daytime,病院等,日中のみ利用される廊下,廊下(日中)
Hospital,Lobby_Daytime,病院等,日中のみ利用されるロビー,ロビー(日中)
Hospital,Toilet_Daytime,病院等,日中のみ利用される共用部の便所,便所(日中)
Hospital,SmokingRoom_Daytime,病院等,日中のみ利用される喫煙室,喫煙室(日中)
Hospital,Kitchen,病院等,厨房,
Hospital,IndoorParking,病院等,屋内駐車場,
Hospital,MechanicalRoom,病院等,機械室,
Hospital,ElectricalRoom,病院等,電気室,
Hospital,Kitchenette,病院等,湯沸室等,
Hospital,StorageRoom,病院等,食品庫等,
Hospital,CopyRoom,病院等,印刷室等,
Hospital,GarbageStorage,病院等,廃棄物保管場所等,ゴミ置場等
Store,LargeScaleRetailStore,物品販売業を営む店舗等,大型店の売場,大型店売場
Store,SpecializedStore,物品販売業を営む店舗等,専門店の売場,専門店売場
Store,Supermarket,物品販売業を営む店舗等,スーパーマーケットの売場,スーパー売場
Store,Backyard,物品販売業を営む店舗等,荷さばき場,
Store,OfficeRoom,物品販売業を営む店舗等,事務室,
Store,LockerRoom,物品販売業を営む店舗等,更衣室又は倉庫,更衣室・倉庫
Store,Lobby,物品販売業を営む店舗等,ロビー,
Store,Toilet,物品販売業を営む店舗等,便所,
Store,SmokingRoom,物品販売業を営む店舗等,喫煙室,
Store,Kitchen,物品販売業を営む店舗等,厨房,
Store,IndoorParking,物品販売業を営む店舗等,屋内駐車場,
Store,MechanicalRoom,物品販売業を営む店舗等,機械室,
Store,ElectricalRoom,物品販売業を営む店舗等,電気室,
Store,Kitchenette,物品販売業を営む店舗等,湯沸室等,
Store,StorageRoom,物品販売業を営む店舗等,食品庫等,
Store,CopyRoom,物品販売業を営む店舗等,印刷室等,
Store,GarbageStorage,物品販売業を営む店舗等,廃棄物保管場所等,ゴミ置場等
School,ClassroomInPrimarySchool,学校等,小中学校の教室,小中学校教室
School,ClassroomInHighSchool,学校等,高等学校の教室,高校教室
School,StaffRoom,学校等,職員室,
School,SchoolCanteen,学校等,小中学校又は高等学校の食堂,小中高校食堂
School,ClassroomInCollege,学校等,大学の教室,大学教室
School,CollegeCanteen,学校等,大学の食堂,大学食堂
School,OfficeRoom,学校等,事務室,
School,ResearchRoom,学校等,研究室,
School,ComputerRoom,学校等,電子計算機器演習室,コンピュータ室
School,Laboratory,学校等,実験室,
School,PracticalRoom,学校等,実習室,
School,Hall,学校等,講堂又は体育館,講堂・体育館
School,NightDutyRoom,学校等,宿直室,
School,LockerRoom,学校等,更衣室又は倉庫,更衣室・倉庫
School,Corridor,学校等,廊下,
School,Lobby,学校等,ロビー,
School,Toilet,学校等,便所,
School,SmokingRoom,学校等,喫煙室,
School,Kitchen,学校等,厨房,
School,IndoorParking,学校等,屋内駐車場,
School,MechanicalRoom,学校等,機械室,
School,ElectricalRoom,学校等,電気室,
School,Kitchenette,学校等,湯沸室等,
School,StorageRoom,学校等,食品庫等,
School,CopyRoom,学校等,印刷室等,
School,GarbageStorage,学校等,廃棄物保管場所等,ゴミ置場等
Restaurant,Restaurant,飲食店等,レストランの客室,レストラン客室
Restaurant,LightRestaurant,飲食店等,軽食店の客室,軽食店客室
Restaurant,CoffeeShop,飲食店等,喫茶店の客室,喫茶店客室
Restaurant,Bar,飲食店等,バー,
Restaurant,FrontDesk,飲食店等,フロント,
Restaurant,OfficeRoom,飲食店等,事務室,
Restaurant,LockerRoom,飲食店等,更衣室又は倉庫,更衣室・倉庫
Restaurant,Corridor,飲食店等,廊下,
Restaurant,Lobby,飲食店等,ロビー,
Restaurant,Toilet,飲食店等,便所,
Restaurant,SmokingRoom,飲食店等,喫煙室,
Restaurant,Kitchen,飲食店等,厨房,
Restaurant,IndoorParking,飲食店等,屋内駐車場,
Restaurant,MechanicalRoom,飲食店等,機械室,
Restaurant,ElectricalRoom,飲食店等,電気室,
Restaurant,Kitchenette,飲食店等,湯沸室等,
Restaurant,StorageRoom,飲食店等,食品庫等,
Restaurant,CopyRoom,飲食店等,印刷室等,
Restaurant,GarbageStorage,飲食店等,廃棄物保管場所等,ゴミ置場等
MeetingPlace,GymnasiumInAthletic,集会所等,アスレチック場の運動室,アスレチック場運動室
MeetingPlace,LobbyInAthletic,集会所等,アスレチック場のロビー,アスレチック場ロビー
MeetingPlace,ToiletInAthletic,集会所等,アスレチック場の便所,アスレチック場便所
MeetingPlace,SmokingRoomInAthletic,集会所等,アスレチック場の喫煙室,アスレチック場喫煙室
MeetingPlace,SkatingRinkForOfficialCompetition,集会所等,公式競技用スケート場,スケート場(公式)
MeetingPlace,ArenaForOfficialCompetition,集会所等,公式競技用体育館,体育館(公式)
MeetingPlace,SkatingRinkForGeneralGame,集会所等,一般競技用スケート場,スケート場(一般)
MeetingPlace,ArenaForGeneralGame,集会所等,一般競技用体育館,体育館(一般)
MeetingPlace,SkatingRinkForRecreation,集会所等,レクリエーション用スケート場,スケート場(レク)
MeetingPlace,ArenaForRecreation,集会所等,レクリエーション用体育館,体育館(レク)
MeetingPlace,CheeringSectionInStadium,集会所等,競技場の客席,競技場応援席
MeetingPlace,LobbyInStadium,集会所等,競技場のロビー,競技場ロビー
MeetingPlace,ToiletInStadium,集会所等,競技場の便所,競技場便所
MeetingPlace,SmokingRoomInStadium,集会所等,競技場の喫煙室,競技場喫煙室
MeetingPlace,BathroomInBathingFacility,集会所等,公衆浴場の浴室,浴場施設の浴室
MeetingPlace,LockerRoomInBathingFacility,集会所等,公衆浴場の脱衣所,浴場施設の脱衣所
MeetingPlace,RestingRoomInBathingFacility,集会所等,公衆浴場の休憩室,浴場施設の休憩室
MeetingPlace,LobbyInBathingFacility,集会所等,公衆浴場のロビー,浴場施設のロビー
MeetingPlace,ToiletInBathingFacility,集会所等,公衆浴場の便所,浴場施設の便所
MeetingPlace,SmokingRoomInBathingFacility,集会所等,公衆浴場の喫煙室,浴場施設の喫煙室
MeetingPlace,AuditoriumInMovieTheater,集会所等,映画館の客席,映画館観客席
MeetingPlace,LobbyInMovieTheater,集会所等,映画館のロビー,映画館ロビー
MeetingPlace,ToiletInMovieTheater,集会所等,映画館の便所,映画館便所
MeetingPlace,SmokingRoomInMovieTheater,集会所等,映画館の喫煙室,映画館喫煙室
MeetingPlace,Library,集会所等,図書館の図書室,図書館図書室
MeetingPlace,LobbyInLibrary,集会所等,図書館のロビー,図書館ロビー
MeetingPlace,ToiletInLibrary,集会所等,図書館の便所,図書館便所
MeetingPlace,SmokingRoomInLibrary,集会所等,図書館の喫煙室,図書館喫煙室
MeetingPlace,Museum,集会所等,博物館の展示室,博物館展示室
MeetingPlace,LobbyInMuseum,集会所等,博物館のロビー,博物館ロビー
MeetingPlace,ToiletInMuseum,集会所等,博物館の便所,博物館便所
MeetingPlace,SmokingRoomInMuseum,集会所等,博物館の喫煙室,博物館喫煙室
MeetingPlace,DressingRoom,集会所等,劇場の楽屋,劇場楽屋
MeetingPlace,BoardInTheater,集会所等,劇場の舞台,劇場舞台
MeetingPlace,AudienceSeatInTheater,集会所等,劇場の客席,劇場観客席
MeetingPlace,LobbyInTheater,集会所等,劇場のロビー,劇場ロビー
MeetingPlace,ToiletInTheater,集会所等,劇場の便所,劇場便所
MeetingPlace,SmokingRoomInTheater,集会所等,劇場の喫煙室,劇場喫煙室
MeetingPlace,Karaoke,集会所等,カラオケボックス,
MeetingPlace,Bowlling,集会所等,ボーリング場,
MeetingPlace,Pachinko,集会所等,ぱちんこ屋,
MeetingPlace,AuditoriumInRaceCourse,集会所等,競馬場又は競輪場の客席,競馬競輪場観客席
MeetingPlace,TicketOfficeInRaceCourse,集会所等,競馬場又は競輪場の券売場,競馬競輪場券売場
MeetingPlace,ShopInRaceCourse,集会所等,競馬場又は競輪場の店舗,競馬競輪場店舗
MeetingPlace,LobbyInRaceCourse,集会所等,競馬場又は競輪場のロビー,競馬競輪場ロビー
MeetingPlace,ToiletInRaceCourse,集会所等,競馬場又は競輪場の便所,競馬競輪場便所
MeetingPlace,SmokingRoomInRaceCourse,集会所等,競馬場又は競輪場の喫煙室,競馬競輪場喫煙室
MeetingPlace,MainHallInTemple,集会所等,社寺の本殿,社寺本殿
MeetingPlace,LobbyInTemple,集会所等,社寺のロビー,社寺ロビー
MeetingPlace,ToiletInTemple,集会所等,社寺の便所,社寺便所
MeetingPlace,SmokingRoomInTemple,集会所等,社寺の喫煙室,社寺喫煙室
MeetingPlace,Kitchen,集会所等,厨房,
MeetingPlace,IndoorParking,集会所等,屋内駐車場,
MeetingPlace,MechanicalRoom,集会所等,機械室,
MeetingPlace,ElectricalRoom,集会所等,電気室,
MeetingPlace,Kitchenette,集会所等,湯沸室等,
MeetingPlace,StorageRoom,集会所等,食品庫等,
MeetingPlace,CopyRoom,集会所等,印刷室等,
MeetingPlace,GarbageStorage,集会所等,廃棄物保管場所等,ゴミ置場等
Factory,WareHouse,工場等,倉庫,
Factory,OutdoorParikng,工場等,屋外駐車場又は駐輪場,屋外駐車駐輪場
ApartmentHouse,IndoorCorridor,共同住宅,屋内廊下,
ApartmentHouse,Lobby,共同住宅,ロビー,
ApartmentHouse,ManagerRoom,共同住宅,管理人室,
ApartmentHouse,AssemblyRoom,共同住宅,集会室,
ApartmentHouse,OutdoorCorridor,共同住宅,屋外廊下,
ApartmentHouse,IndoorParking,共同住宅,屋内駐車場,
ApartmentHouse,MechanicalRoom,共同住宅,機械室,
ApartmentHouse,ElectricalRoom,共同住宅,電気室,
ApartmentHouse,GarbageStorage,共同住宅,廃棄物保管場所等,ゴミ置場等
Common,NonACRoom,共通,非空調室,非空調室
|===

=== 有無の変換ルール

「有」と「無」を選択要素とする選択項目は、以下の表の通り変換する。

.有無の変換
[[Boolean]]
[options="header"]
|===
|XMLの値 |CSVの値

|False |無
|True |有
|===

=== 非主要室の変換

主要室入力法による非主要室は、各設備の対象室の要素へ変換する代わりに、MinorRoom要素へ変換する。

.非主要室の変換
[[MinorRoom]]
[options="header"]
|===
|XML要素 |値

|Floor |①階
|Name |①室名
|BuildingType |①建物用途
|RoomType |①室用途（ `"非主要室"` ）
|Area |①室面積
|===
