== 様式8. 非空調外皮仕様入力シート

①階、①非空調ゾーン名、①建物用途、①室用途、①室面積、①階高が入力されている行を1つの非空調ゾーンの開始行とする。
これらは全て入力されているか、全て空欄でなければならない。
非空調ゾーンの2行目以降では、①階、①非空調ゾーン名、①建物用途、①室用途、①室面積、①階高は入力されない。
①階、①非空調ゾーン名、①建物用途、①室用途、①室面積、①階高が入力されている場合、次の非空調ゾーンの開始行とする。

1行目（非空調ゾーンの開始行）に基づいて、1つのModel/AirConditioningSystems/AirConditioningZone要素と1つのModel/AirConditioningSystems/EnvelopeSet要素に変換する。

.AirConditioningZone要素への変換
[options="header"]
|===
|XML要素 |値

|Floor |①階
|Name |`"非空調_"` + ①非空調ゾーン名
|NonAC |`True`
|RoomRef |非空調ゾーン1つに対して1つのRoomRef要素
|===

.非空調ゾーンのRoomRef要素
[options="header"]
|===
|XML要素 |値

|Floor |①階
|Name |`"非空調_"` + ①非空調ゾーン名
|BuildingType |①建物用途を<<building-type>>に基づいて変換
|RoomType |①室用途を<<building-type>>に基づいて変換
|Area |①室面積
|FloorHeight |①階高
|===

.EnvelopeSet要素への変換
[options="header"]
|===
|XML要素 |値

|ACZoneFloor |①階
|ACZoneName |`"非空調_"` + ①非空調ゾーン名
|Envelope |非空調ゾーンの行に対して1つのEnvelope要素
|===

②方位、④外壁名称、⑤外皮面積が入力されている行を1つの外皮の開始行とする。
これらは全て入力されているか、全て空欄でなければならない。
非空調ゾーンの1行目は、必ず外皮の1行目も兼ねる（つまり、①階、①空調ゾーン名、①建物用途、①室用途、①室面積、①階高、②方位、④外壁名称、⑤外皮面積が入力されていなければならない）。
②方位、④外壁名称、⑤外皮面積が入力されている場合、次の外皮の開始行とする。

非空調ゾーンの行に対して1つのModel/AirConditioningSystems/EnvelopeSet/Envelope要素を以下の通り変換する。

.Envelope要素への変換
[options="header"]
|===
|XML要素 |値

|Direction |②方位を<<Direction>>に基づいて変換
|WallConfiguration |④外壁名称
|Area |⑤外皮面積(窓含)
|Window |開口部の行に対して1つのWindow要素。開口部がない場合、Window要素は存在しない。
|===

⑥開口部名称、⑦窓面積が入力されている行を1つの開口部の行とする。
これらは全て入力されているか、全て空欄でなければならない。
外皮の開始行に⑥開口部名称、⑦窓面積が入力されていない場合、当該外皮には開口部がないものとする。
該当する行に対して1つのModel/AirConditioningSystems/EnvelopeSet/Envelope/Window要素を以下の通り変換する。

.Window要素への変換
[options="header"]
|===
|XML要素 |値

|CoolingEaves |③日よけ効果係数(冷房)
|HeatingEaves |③日よけ効果係数(暖房)
|WindowSpecification |⑥開口部名称
|Area |⑦窓面積
|Blind |⑧ブラインドの有無を<<Boolean>>に基づいて変換
|===

