:lang: ja
:doctype: book
:toc: left
:toclevels: 4
:toc-title: 第9章 目次
:sectnums!:
:sectnumlevels: 4
:sectlinks:
:linkattrs:
:icons: font
:source-highlighter: coderay
:example-caption: 例
:table-caption: 表
:figure-caption: 図
:docname: = 平成28年省エネルギー基準一次エネルギー消費量算定方法の解説（非住宅建築物）
:stem: latexmath
:xrefstyle: short

= 平成28年 省エネルギー基準 一次エネルギー消費量算定方法の解説（非住宅建築物）

国土交通省 国土技術政策総合研究所、国立研究開発法人 建築研究所

link:./index.html[トップページに戻る]

== 9. その他一次エネルギー消費量の算定方法

その他一次エネルギー消費量の算定ロジックを示す。

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[ROOMTYPE_{M,r}]| 計算対象室rの建物用途・室用途 | - | 様式1：①建物用途、室用途|
stem:[A_{M,r}]| 計算対象室rの床面積 |m^2^| 様式1：①室面積|
stem:[n_{M}]| 計算対象室の数 | - | 様式1：①室名 の総入力行数|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{M}]|その他一次エネルギー消費量| MJ/年 ||
|=================================

その他一次エネルギー消費量 stem:[E_{M}] [MJ/年] は、次式で算出する。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{M} = \sum_{r=1}^{n_{M}} (a_{M,r} \times A_{M,r} )
++++++++++++++++++++++++++++++++++++++++++++
====

係数 stem:[a_{M,r}] [MJ/（m^2^・年）]は 国交省平成28年告示265号別表第2 で規定されている値であり、床面積あたりのその他一次エネルギー消費量である。

この係数は、計算対象室rの室用途毎に規定されており、
計算対象室 r の様式1：①建物用途、室用途( stem:[ROOMTYPE_{M,r}] )の情報から、国交省平成28年告示265号 別表第2 より該当する係数 stem:[a_{M,r}] を抽出する。

式中のΣは、入力シートに入力された全ての計算対象室について積算することを意味しており、具体的には「様式1 室仕様入力シート」に入力された全ての室について積算を行う。 +

ここで、係数 stem:[a_{M,r}] は、各室用途の標準室使用条件における機器発熱量の年間積算値を一次エネルギー換算した値であり、算定式は次式のとおりである。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
a_{M,r} = \sum_{d=1}^{365} \sum_{t=1}^{24} (Q_{app,r,d,t}) \times f_{prime,e} \times 10^{-6}
++++++++++++++++++++++++++++++++++++++++++++
====

式中の stem:[Q_{app,r,d,t}] は日付d、時刻tにおける室の機器発熱量［W/m^2^］であり、室用途毎に標準室使用条件で定められている。
なお、一部の室用途については、待機電力を想定して非空調時間帯における機器発熱量を見込んでいるが、その他エネルギー消費量の計算には、この非空調時間帯の機器発熱量も含めて算出するものとする。 +
標準室使用条件において、非空調室用途（空気調和設備の基準値が設定されていない室用途）については機器発熱量は常に0であるとされているため、
非空調室用途については係数 stem:[a_{M,r}] は0である。


