:lang: ja
:doctype: book
:toc: left
:toclevels: 4
:toc-title: 第5章 目次
:sectnums!:
:sectnumlevels: 4
:sectlinks:
:linkattrs:
:icons: font
:source-highlighter: coderay
:example-caption: 例
:table-caption: 表
:figure-caption: 図
:docname: = 平成28年省エネルギー基準一次エネルギー消費量算定方法の解説（非住宅建築物）
:stem: latexmath
:xrefstyle: short

= 平成28年 省エネルギー基準 一次エネルギー消費量算定方法の解説（非住宅建築物）

国土交通省 国土技術政策総合研究所、国立研究開発法人 建築研究所

link:./index.html[トップページに戻る]


== 5. 給湯設備の評価方法

給湯設備の一次エネルギー消費量算出ロジックを示す。


=== 5.1 はじめに

==== 5.1.1 適用範囲

計算の対象とする給湯設備は、次のように定義する。 

[loweralpha]
. 二管式の給湯設備
* 例えば、病院やホテル等の循環給湯設備、瞬間湯沸かし機を連結したマルチ型の循環式給湯 機
. 一管式の給湯設備
* 返湯管のない中央式給湯機
* 便所の手洗い用給湯機など、熱源機器と給湯栓が1対1に対応する局所式給湯設備

次の給湯設備は対象とはしない。
[loweralpha]
. オフィスや待合に設置される個別の給茶器、自動販売機
. 給湯栓を有しない給湯設備(7 号給湯器等)
. 雑用水利用のための給湯設備(洗濯機用等)
. 循環加温用のための給湯設備(浴場施設や温水プールの加温のための設備)。ただし、浴場施設や温水プールであっても、シャワーや洗面用途のための給湯設備は対象とする。


==== 5.1.2 用語の定義

. *日積算給湯負荷* +
給湯システムが一日に生成する熱量の総和。給湯システムがサービスを供給する室が要求する熱量と等しい。単位はkJ/日。

. *日積算配管熱損失* +
給湯システムの配管からの一日の損失熱量の総和。単位はkJ/日。

. *給湯システム数* +
計算対象建物内に設置される給湯システムの数。

. *給湯温度* +
水栓から出る湯の温度。単位は℃。

. *日平均給水温度* +
給湯システムに給水される水の温度。単位は℃。

. *日積算給湯量* +
給湯システムが一日に供給する湯量の総和。単位はL/日。

. *循環水温度* +
給湯システムの配管内を循環する湯の温度。単位は℃。

. *配管周囲温度* +
配管周囲の空気温度。単位は℃。

. *配管の線熱損失係数* +
配管の熱の伝わりやすさを表す指標。配管内外温度差が1Kの時の配管1mあたりの熱通過量で表す。単位はW/（m・K）。

. *給湯対象室* +
給湯設備を利用する可能性がある人が存在する居室。


==== 5.1.3 共通の定数

本章で使用する共通の定数を以下に示す。

.定数
[options="header", cols="2,5,2,1"]
|=================================
|定数名|説明|値|単位|
stem:[c_{w}]|水の比熱|4.2|kJ/(kg・K)|
|=================================



<<<<
==== 5.1.4 入出力

本章全体における入力、出力は下表の通りである。

.入力
[options="header", cols="2,5,2,4"]
|===
|変数名|説明|単位|入力シート
// D.1
|stem:[BuildingType]|建物用途|-|様式5-1：①建物用途・室用途
|stem:[RoomType_{i}]|室iの室用途|-|様式5-1：①建物用途・室用途
// D.4
|stem:[ClimateZone]|評価対象建築物の地域区分|-|様式0：⑤省エネ基準地域区分
// D.5
|stem:[k_{W,i}]|配管接続口径|-|様式5-2：⑥接続口径
// 5.2
|stem:[Q_{W,i,r}]|給湯対象室rに温水を提供する給湯設備iの定格加熱能力|kW|様式5-2：③定格加熱能力
// 5.5
|stem:[A_{W,solar,i}]|給湯設備iに属する太陽熱温水器の有効集熱面積|m^2^|様式5-2：⑦有効集熱面積
// 5.7
|stem:[\eta_{W,i}]|給湯設備iの運転効率|-|様式5-2：④熱源効率（一次エネルギー換算）

|===


.出力
[options="header", cols="2,6,2"]
|===
|変数名|説明|単位
|stem:[E_{HW}]|給湯設備の設計一次エネルギー消費量|MJ/年
|===



<<<<
=== 5.2 日積算湯使用量

給湯対象室毎に日積算湯使用量の算出を行う。

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[Q_{W,i,r}]|給湯対象室rに温水を提供する給湯設備iの定格加熱能力|kW|様式5-2：③定格加熱能力|
// stem:[n_{W,r}]|給湯対象室rに温水を提供する給湯設備の台数|台|入力|
stem:[V_{WS1,r,d}]|日付dにおける給湯対象室rの標準日積算湯使用量（洗面のための湯使用量）|L/日|D.1|
stem:[V_{WS2,r,d}]|日付dにおける給湯対象室rの標準日積算湯使用量（シャワーのための湯使用量）|L/日|D.1|
stem:[V_{WS3,r,d}]|日付dにおける給湯対象室rの標準日積算湯使用量（厨房のための湯使用量）|L/日|D.1|
stem:[V_{WS4,r,d}]|日付dにおける給湯対象室rの標準日積算湯使用量（その他の湯使用量）|L/日|D.1|
stem:[\phi_{Wa,i,r}]|給湯対象室rに温水を提供する給湯設備iのための節湯器具（自動給湯栓）による湯使用量削減率|-|D.3|
stem:[\phi_{Wb,i,r}]|給湯対象室rに温水を提供する給湯設備iのための節湯器具（節湯B1）による湯使用量削減率|-|D.3|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[V_{W,i,d}]|日付dにおける給湯設備iによる日積算湯供給量|L/日|5.3、5.4、5.5、5.6|
|=================================

まず、給湯対象室rの節湯器具による湯使用量削減効果を加味した日付dにおける室rの日積算湯使用量 stem:[V_{WR,r,d}] を次式で算出する。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{WR,r,d} = \sum_{i=1}\left\{(V_{WS1,r,d} \times \phi_{Wa,i,r} + V_{WS2,r,d} \times \phi_{Wb,i,r} + V_{WS3,r,d} + V_{WS4,r,d}) \times \frac{Q_{W,i,r}}{ \sum_{i=1}Q_{W,i,r} }\right\}
++++++++++++++++++++++++++++++++++++++++++++
====

次に、日付dにおける給湯対象室rに温水を提供する給湯設備iからの日積算湯供給量（給湯設備iから室rへの日積算湯供給量） stem:[V_{W,i,r,d}] を算出する。

<<<<
ただし、stem:[V_{W,i,r,d}] は、給湯対象室rが、a)給湯設備iからしか温水が提供されない場合と、b)給湯設備i以外の給湯設備からも温水が提供される場合で、次のように算出方法が異なる。

a）給湯対象室rが給湯設備iからしか温水を提供されない場合

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{W,i,r,d} = V_{WR,r,d} 
++++++++++++++++++++++++++++++++++++++++++++
====

b）給湯対象室rが給湯設備i以外の給湯設備から温水を提供される場合（例えば、給湯対象室が事務室で、男子トイレ、女子トイレに別々に給湯設備がある場合）

　給湯対象室rに温水を提供する給湯設備の定格加熱能力の比率で日積算湯使用量 stem:[V_{WR,r,d}] を按分し、これを stem:[V_{W,i,r,d}] とする。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{W,i,r,d} = V_{WR,r,d} \times \frac{Q_{W,i,r}}{ \sum_{i=1}Q_{W,i,r} }
++++++++++++++++++++++++++++++++++++++++++++
====

また、給湯対象室rが給湯設備iから温水を供給されない場合は、stem:[V_{W,r,i,d}] は0とする。
====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{W,i,r,d} = 0
++++++++++++++++++++++++++++++++++++++++++++
====

給湯設備iによる日積算湯供給量 stem:[V_{W,i,d}] は、stem:[V_{W,i,r,d}] を全ての給湯対象室について積算した値であるとする。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{W,i,d} = \sum_{r=1}V_{W,i,r,d}
++++++++++++++++++++++++++++++++++++++++++++
====



<<<<
=== 5.3 配管長さ

給湯配管の長さを算出する。省エネルギー基準では、評価・審査の簡略化の観点から、
実際の配管長さを詳細に入力するのではなく、日積算湯使用量から推定することとしている。


.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[V_{W,i,d}]|日付dにおける給湯設備iの日積算湯使用量|L/日|5.2|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[L_{W,i}]| 給湯設備iの配管長さ|m|5.4|
|=================================

.定数
[options="header", cols="2,5,2,1"]
|=================================
|定数名|説明|単位|値|
stem:[Ix_{SW}]|基準設定Ix値|-|7| 
|=================================

　配管長さ stem:[L_{W,i}] は、次式で算出する。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
L_{W,i} =  \frac{V_{SW,i}}{1000} \times Ix_{SW}
++++++++++++++++++++++++++++++++++++++++++++
====

　給湯設備iの日積算湯使用量の平均値 stem:[V_{SW,i}]［L/日］は、stem:[V_{W,i,d}]が最大となる日の値を使用する。

　Ix値は、総配管長を日積算湯使用量で除した値として定義されており、旧基準においては、この値によってCEC/HWの基準値が定められていた。
平成25年基準においては、申請及び審査の簡略化の観点から配管長を図面から読み取る作業を省略したが、この基準設定Ix値 stem:[Ix_{SW}]| を7と定め、
給湯負荷によって仮想的な配管長が定まり、この配管長下における熱損失量を算出することにした。
なお、基準一次エネルギー消費量を求める際の基準設定機器効率は、Ix値が7の場合の旧基準の基準値CEC/HW=1.5から定めているため、旧基準とほぼ同レベルの基準となっている。



<<<<
=== 5.4 年間配管熱損失量

配管からの熱損失量の年間積算値を算出する。


.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[V_{W,i,d}]|日付dにおける給湯設備iによる日積算湯供給量|L/日|5.2|
stem:[L_{W,i}]|給湯設備iの配管長さ|m|5.3|
stem:[\theta_{amb,d}]|日付dにおける配管周囲温度|℃|D.4|
stem:[k_{W,i}]|給湯設備iの配管の線熱損失係数|W/(m・K)|D.5|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[Q_{Wp,i}]|給湯設備iの年間配管熱損失量|kJ/年|5.7|
|=================================

.定数
[options="header", cols="2,5,2,1"]
|=================================
|定数名|説明|単位|値|
stem:[\theta_{Wp}]|循環水温度|℃|60|
stem:[T_{W,i,d}]|日付dにおける給湯設備iの運転時間|時間/日|24|
|=================================

　給湯設備iの年間配管熱損失量 ［kJ/年］は、次式により算出する。給湯設備iによる湯の供給がない日は、配管熱損失がないものとする。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
Q_{Wp,i} = \sum_{d=1}^{365} Q_{Wp,i,d}
++++++++++++++++++++++++++++++++++++++++++++
[stem]
++++++++++++++++++++++++++++++++++++++++++++
Q_{Wp,i,d} = \begin{cases}
(L_{W,i} \times k_{W,i} \times (\theta_{Wp} - \theta_{amb,d}) \times 3600 \times T_{W,i,d}) \times 10^{-3} & ,(V_{W,i,d} > 0) \\
0 & ,(V_{W,i,d} = 0)
\end{cases}
++++++++++++++++++++++++++++++++++++++++++++
====



<<<<
=== 5.5 太陽熱利用システムの熱利用量

太陽熱利用システムの熱利用量の算出を行う。

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[A_{Wsolar,i}]|給湯設備iに属する太陽熱温水器の有効集熱面積|m^2^|様式5-2：⑦有効集熱面積|
stem:[I_{Wds,d}]|日付dにおける当該地域の集熱面日射量|MJ/(m^2^・日)|2.4.1に集熱面の方位角と傾斜角を代入して求める|
stem:[V_{W,i,d}]|日付dにおける給湯設備iによる日積算湯供給量|L/日|5.2|
stem:[\theta_{Win,d}]|日付dにおける日平均給水温度|℃|D.6|
stem:[\theta_{AC,oa,d}]|日付dにおける日平均外気温度|℃|2.2.3|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[Q_{Wsolar,i,d}]|日付dにおける給湯設備iの太陽熱利用システムの熱利用量|kJ/日|5.6|
|=================================

.定数
[options="header", cols="2,5,2,1"]
|=================================
|定数名|説明|単位|値|
stem:[c_{Weff}]|太陽熱温水器の集熱効率 |-|0.40|
stem:[c_{Wsolar}]|太陽熱温水器を補助熱源に接続した場合の、配管ロスを考慮した効率|-|0.85|
stem:[\theta_{Wtap}]|給湯温度|℃|43|
|=================================

<<<<
日付dにおける給湯設備の太陽熱利用システムの熱利用量 は、次のように算出する。

a）太陽熱利用システムがない場合

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
Q_{Wsolar,i,d} = 0
++++++++++++++++++++++++++++++++++++++++++++
====

b）太陽熱利用システムがある場合

　b-1） 日平均外気温が5℃以下である場合
====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
Q_{Wsolar,i,d} = 0
++++++++++++++++++++++++++++++++++++++++++++
====

　b-2） 日平均外気温が5℃を超える場合
====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
Q_{Wsolar,i,d} = A_{Wsolar} \times I_{Wds,d} \times c_{Weff} \times c_{Wsolar}
++++++++++++++++++++++++++++++++++++++++++++
====

ただし、stem:[Q_{Wsolar,i,d}] が 
stem:[c_{w} \times \rho_{w} \times (\theta_{Wtap} - \theta_{Win,d}) \times V_{W,i,d}] の90%以上となる場合は、全てを太陽熱で賄うことはできないとし、次式で算出する。
====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
Q_{Wsolar,i,d} = 0.9 \times A_{Wsolar} \times I_{Wds,d} \times c_{Weff} \times c_{Wsolar}
++++++++++++++++++++++++++++++++++++++++++++
====
とする。

（注）この算出方法は、（財）建築環境・省エネルギー機構「住宅事業建築主の判断の基準におけるエネルギー消費量計算方法の解説」に記載されている算出方法と同じである。



<<<<
=== 5.6 年間給湯負荷

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[V_{W,i,d}]|日付dにおける給湯設備iによる日積算湯供給量|L/日|5.2|
stem:[Q_{Wsolar,i,d}]|日付dにおける給湯設備iの太陽熱利用システムの熱利用量|kJ/日|5.5|
stem:[\theta_{Win,d}]|日付dにおける日平均給水温度|℃|D.6|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[Q_{Wr,i}]|給湯設備iの年間給湯負荷|kJ/年|5.7|
|=================================

.定数
[options="header", cols="2,5,2,1"]
|=================================
|定数名|説明|単位|値|
stem:[\theta_{Wtap}]|給湯温度|℃|43|
|=================================

給湯設備 の年間給湯負荷 stem:[Q_{Wr,i}]［kJ/年］は次式により算出される。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
Q_{Wr,i} = \sum_{d=1}^{365}( c_{w} \times \rho_{w} \times (\theta_{Wtap} - \theta_{Win,d}) \times V_{W,i,d} - Q_{Wsolar,i,d})
++++++++++++++++++++++++++++++++++++++++++++
====



<<<<
=== 5.7 給湯設備の設計一次エネルギー消費量

給湯設備の年間一次エネルギー消費量 stem:[E_{HW}] [MJ/年]を算出する。

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[Q_{Wp,i}]|給湯設備iの年間配管熱損失量|kJ/年|5.4|
stem:[Q_{Wr,i}]|給湯設備iの年間給湯負荷|kJ/年|5.6|
stem:[\eta_{W,i}]|給湯設備iの運転効率（一次エネルギー換算）|-|様式5-2：④熱源効率（一次エネルギー換算）|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{HW}]|給湯設備の設計一次エネルギー消費量|MJ/年|-|
|=================================

.定数
[options="header", cols="2,5,2,1"]
|=================================
|定数名|説明|単位|値|
stem:[C_{W}]|補正係数|-|2.5|
|=================================

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{HW} = \sum_{i=1} ( \frac{ Q_{Wr,i} + C_{W} \times Q_{Wp,i} }{ \eta_{W,i} } ) \times 10^{-3}
++++++++++++++++++++++++++++++++++++++++++++
====

式中の stem:[10^{-3}] は、［kJ］を［MJ］に換算するための係数である。
なお、上式にはポンプの消費電力は明示的に表われていないが、補正係数 の中にポンプの消費電力の影響は含まれている。

運転効率については、一次エネルギー換算された効率であることとし、以下のように算出する。

a)	燃焼式給湯システムの場合 + 
　燃焼式給湯システムの熱源効率 =  +  
　　　　　給湯熱源単体の定格加熱能力[kW]× 3600[kJ/kWh] / (給湯熱源単体の燃料消費量[kJ/h] ＋ 電力消費量[kJ/h])

** 給湯熱源単体の燃料消費量(ガス)[kJ/h]= ガス消費量[m^3^/h]×ガス発熱量(高位)[kJ/m^3^] 

** 給湯熱源単体の燃料消費量(油)[kJ/h]= 油消費量 [L/h] ×比重量[kg /L]×油発熱量(高位)[kJ/kg] 

b)	電気式給湯システムの場合 + 
　電気式給湯熱源効率 = 定格COP × 3600 / 9760 [kJ/kWh] 

** 電気式給湯熱源の定格COP =給湯熱源定格加熱能力[kW] / 給湯熱源定格消費電力[kW] 
** 電気式給湯機のうちヒートポンプを使用する場合、「高温貯湯加熱（冬期）」の値を入力すること。

なお、1つの給湯系統の中に複数の給湯機器が接続されており、これらが連携して動く場合は、
これらの給湯機器の熱源効率を各熱源機器の定格加熱能力で重み付けして平均した値とする。 



<<<<
=== 附属書D（給湯）

==== D.1 標準日積算湯使用量（標準室使用条件）

　標準日積算湯使用量は、給湯対象室rの室用途に応じて定められている。
標準室使用条件は次の4つのファイルにて規定されており、対象室の建物用途・室用途に応じて該当する値を抽出する。

* 建物用途・室用途の一覧： link:https://github.com/WEBPRO-NR/BESJP_Webpro_RouteB/blob/dev/database/ROOM_NAME.csv[ROOM_NAME.csv]
* 室同時使用率等の参照値： link:https://github.com/WEBPRO-NR/BESJP_Webpro_RouteB/blob/dev/database/ROOM_SPEC_H28.csv[ROOM_SPEC.csv]
* 時刻別のスケジュール： link:https://github.com/WEBPRO-NR/BESJP_Webpro_RouteB/blob/dev/database/ROOM_COND.csv[ROOM_COND.csv]
* カレンダーパターン： link:https://github.com/WEBPRO-NR/BESJP_Webpro_RouteB/blob/dev/database/CALENDAR.csv[CALENDAR.csv]


.入力
[options="header", cols="2,5,2,2"]
|=================================
|変数名|説明|単位|参照先|
stem:[BuildingType]|建物用途|-|様式5-1：①建物用途・室用途|
stem:[RoomType_{i}]|室iの室用途|-|様式5-1：①建物用途・室用途|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[V_{WS1,r,d}]|日付dにおける給湯対象室rの標準日積算湯使用量（洗面のための湯使用量）|L/日|5.5|
stem:[V_{WS2,r,d}]|日付dにおける給湯対象室rの標準日積算湯使用量（シャワーのための湯使用量）|L/日|5.5|
stem:[V_{WS3,r,d}]|日付dにおける給湯対象室rの標準日積算湯使用量（厨房のための湯使用量）|L/日|5.5|
stem:[V_{WS4,r,d}]|日付dにおける給湯対象室rの標準日積算湯使用量（その他の湯使用量）|L/日|5.5|
|=================================

標準日積算湯使用量の単位は室用途によって異なり、[L/人日] か [L/m^2^日] で規定されている。
単位については、ROOM_SPEC_H28.csv の AE列 に記されている。
単位が[L/人日]の場合については、ROOM_SPEC_H28.csv の J列で指定される 人員密度参照値 [人/m^2^] を乗じて、床面積あたりの値に変換する。

ここで、「ホテル等・客室」の「シャワー」用途の日積算湯使用量については、以下の想定で算出されている。 + 
　　10.5分／人　×　10 L/分　×　0.75（同時使用率） = 79 L/人 + 

<<<<
    
また、「病院等・病室」の「シャワー」用途については、以下の想定で算出されている。 + 
　　2.1分／人　×　10 L/分　×　0.90（同時使用率） = 21 L/人 + 

上記の式の10.5分／人、2.1分／人は、巧水スタイル推進チームによる link:http://www.takumi-team.jp/wp-content/uploads/2015/02/53fd8eb05f3e38eddeae43d0a7ec71bd.pdf[日本国内のパブリック施設における節水効果について] による。



標準室使用条件より、給湯対象室rの室用途に該当する室使用条件を抽出し、これを給湯対象室rの使用条件とする。 + 

標準室使用条件は室用途毎に定められており、
室用途毎に3つの「基本スケジュール（室使用パターン1, 2, 3）」があり、各日がどの基本スケジュールで動くかは「カレンダーパターン」として定められている。

なお、カレンダーパターンは「CALENDAR.csv」、各室用途がどのカレンダーパターンであるかは「ROOM_SPEC.csv」、 上記のファイルを使用する際に必要となる検索キーは「ROOM_NAME.csv」で規定されている。


* データベースの検索キーを取得する。

建物用途 stem:[BuildingType] と室用途 stem:[RoomType_{i}] を用いて、ROOM_NAME.csvより検索キーを取得する。
====
例）建物用途が「事務所等」で室用途が「事務室」の場合、検索キーは「O-1」となる。
====

* カレンダーパターンコード（A, B, C, D, E, F）を取得する。

検索キーを用いて、ROOM_SPEC.csvよりカレンダーパターンコードを取得する。
====
例）検索キーが「O-1」の場合、カレンダーパターンコードは「A」となる。
====

* 日別のカレンダーパターン（1, 2, 3）を取得する。

日付dとカレンダーコードを用いて、ROOM_CALENDAR.csvよりカレンダーパターンを取得する。
====
例）日付dが「1月1日」でカレンダーコードが「A」の場合、日付dにおけるカレンダーパターンは「3」となる。
====

* 時刻別室同時使用率を取得する。

検索キーとカレンダーパターンを用いて、ROOM_COND.csvより室同時使用率を取得する。
====
例）検索キーが「O-1」、カレンダーパターンが「3」の場合、0時の室同時使用率（T0）は「0」となる。
====

* 日別積算室同時使用率を取得する。

時刻別室同時使用率を日積算し日積算室同時使用率を取得する。
====
例）検索キーが「O-1」、カレンダーパターンが「3」の場合、日積算室同時使用率（T0~T23の積算）は「0」となる。
====

<<<<
給湯対象室rについて、日付dにおける室同時使用率の日積算値が0より大きければ「日付dにおいて室rは使用されている」と判断する。
一方、この日積算値が0であれば、「日付dにおいて室rは使用されていない」と判断する。 + 
日付dにおいて室rが使用されている　と判断されれば　日付dにおける給湯利用の有無 stem:[\phi_{WS,r,d}] は　1　とし、
日付dにおいて室rが使用されていない　と判断されれば　日付dにおける給湯利用の有無 stem:[\phi_{WS,r,d}] は　0 とする。


====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{WS1,r,d} =  V_{WS1,r} \times \phi_{WS,r,d}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{WS2,r,d} =  V_{WS2,r} \times \phi_{WS,r,d}
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{WS3,r,d} =  V_{WS3,r} \times \phi_{WS,r,d} 
++++++++++++++++++++++++++++++++++++++++++++

[stem]
++++++++++++++++++++++++++++++++++++++++++++
V_{WS4,r,d} =  V_{WS4,r} \times \phi_{WS,r,d} 
++++++++++++++++++++++++++++++++++++++++++++
====



<<<<
==== D.2 配管保温仕様

配管保温仕様は、下表のとおり「管径」と「保温材の厚さ」から定まる。

.配管保温仕様
[options="header", cols="2,7"]
|=================================
|選択肢|定義（保温材の厚さ）|
保温仕様1|
管径が40㎜未満の配管にあっては、保温材の厚さが30㎜以上 + 
管径が40㎜以上125㎜未満の配管にあっては、保温材の厚さが40㎜以上 + 
管径が125㎜以上の配管にあっては、保温材の厚さが50㎜以上|
保温仕様2|
管径が50㎜未満の配管にあっては、保温材の厚さが20㎜以上 + 
管径が50㎜以上125㎜未満の配管にあっては、保温材の厚さが25㎜以上 + 
管径が125㎜以上の配管にあっては、保温材の厚さが30㎜以上|
保温仕様3|
管径が125㎜未満の配管にあっては、保温材の厚さが20㎜以上 + 
管径が125㎜以上の配管にあっては、保温材の厚さが25㎜以上|
裸管|
上記記の保温仕様1,2,3に該当しないもの|
|=================================

<<<<
==== D.3 節湯器具による湯使用量削減率

湯使用量削減率は、節湯器具の種類毎に定められている。

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[\phi_{Wa,i,r}]|室rに温水を提供する給湯機器iとの接続で使用される自動給湯栓による湯使用量削減率|-|5.2|
stem:[\phi_{Wb,i,r}]|室rに温水を提供する給湯機器iとの接続で使用される節湯B1による湯使用量削減率|-|5.2|
|=================================

まず、節湯器具の種類及びその定義は以下の通りとする。

.節湯器具の種類
[options="header", cols="2,5"]
|=================================
|選択肢	|定義|
自動給湯栓|洗面に設置され、使用と共に自動で止水する給湯栓。電気的に開閉し、手を遠ざけると自動で止水するもの。 + 
なお、公衆浴場等で使用される自閉式水栓（一定時間量を吐出した後に自動で止水する水栓）については、広く普及しており、日積算湯使用量原単位の中にその節湯効果が既に見込まれているため、「自動給湯栓」とはみなさないこととする。|
節湯B1（小流量吐水機構）|
基準（http://www.j-valve.or.jp/suisen/setsuyu/f_setsuyu-a1b1c1-kijun_201405.pdf）に定められた試験方法にて吐水力を測定し、その値が次の条件に適合すること。 + 
* 流水中に空気を混入させる構造を 持たないもの → 0.60 N以上  +
* 流水中に空気を混入させる構造を 持つもの → 0.55 N以上 |

無|
上記の機構を有する水栓以外すべて。
なお、「2バルブ水栓」を採用する場合は、上記の機構の有無によらず「無」とする。 + 
* 室rの全ての給湯栓が「自動給湯栓」もしくは「節湯B1」に合致しなければ、節湯器具を採用したとはみなさないこととする。 + 
* 節湯A１（手元止水機構）、節湯C1（水優先吐水機構）については、非住宅建築物に設置された場合の節湯効果が不明瞭であるため（家庭用と業務用では湯水の使われ方が異なる）、非住宅建築物の評価法においては節湯器具とはみなさない。|

|=================================

　湯使用量削減率は次のとおりとする。

** 自動給湯栓が設置される場合は stem:[\phi_{Wa,i,r}]=0.6、設置されない場合は stem:[\phi_{Wa,i,r}]=1.0

** 節湯B1が設置される場合は、 stem:[\phi_{Wb,i,r}]=0.75（節水型シャワーノズル15%、サーモスタット10%で合わせて25%削減）とする。設置されない場合は stem:[\phi_{Wb,i,r}]=1.0

　ただし、「自動給湯栓」と「節湯B1」が同時に設置されることはないものとする。



<<<<
==== D.4 配管周囲温度

配管周囲温度は地域区分によって定められている。

.入力
[options="header", cols="2,5,2,2"]
|=================================
|変数名|説明|単位|参照先|
stem:[ClimateZone]|評価対象建築物の所在地の地域区分|-|様式0：⑤省エネ基準地域区分|
stem:[\theta_{oa,d}]|日付dにおける日平均外気温|℃|2.2.3|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[\theta_{amb,d}]|日付dにおける配管周囲温度|℃|5.4|
|=================================

配管周囲温度 stem:[\theta_{amb,d}] は日平均外気温と室温との平均値とする。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
\theta_{amb,d} = \frac{ \theta_{oa,d} + \theta_{room,d}}{ 2 }
++++++++++++++++++++++++++++++++++++++++++++
====

日平均外気温は、地域区分から気象データ内の外気温度が読み込み、これを元に算出する。
室温 stem:[\theta_{room,d}] は下表のように地域毎に暖房期、中間期、冷房期を定め（これは空調機の運転モードの設定と同じである）、
暖房期は22℃、中間期は24℃、冷房期は26℃とする。

.空調機の運転モードの設定
[format="csv", options="header" cols="2,12*1"]
|=================================
地域区分,1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月
1地域,暖房,暖房,暖房,暖房,中間,中間,冷房,冷房,冷房,中間,暖房,暖房
2地域,暖房,暖房,暖房,暖房,中間,中間,冷房,冷房,冷房,中間,暖房,暖房
3地域,暖房,暖房,暖房,中間,中間,冷房,冷房,冷房,冷房,中間,中間,暖房
4地域,暖房,暖房,暖房,中間,中間,冷房,冷房,冷房,冷房,中間,中間,暖房
5地域,暖房,暖房,暖房,中間,中間,冷房,冷房,冷房,冷房,中間,中間,暖房
6地域,暖房,暖房,暖房,中間,中間,冷房,冷房,冷房,冷房,中間,中間,暖房
7地域,暖房,暖房,暖房,中間,中間,冷房,冷房,冷房,冷房,中間,中間,暖房
8地域,暖房,暖房,暖房,中間,冷房,冷房,冷房,冷房,冷房,冷房,中間,中間
|=================================


<<<<
==== D.5 給湯配管の線熱損失係数

給湯配管の線熱損失係数 stem:[k_{W,i}] [W/m・K]は、配管の保温仕様（D.2）及び配管接続口径 stem:[k_{W,i}]［㎜］（入力）を基に、下表により求める。

.入力
[options="header", cols="2,5,2,2"]
|=================================
|変数名|説明|単位|参照先|
stem:[Type_{insulation,pipe}]|配管の保温仕様|-|D.2|
stem:[k_{W,i}]|配管接続口径|mm|様式5-2：⑥接続口径|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[k_{W,i}]|給湯配管の線熱損失係数|W/(m・K)|5.4|
|=================================

.配管の熱伝導率
[options="header", cols="5,3,3,3,3"]
|=================================
|配管接続口径 | 保温仕様1 | 保温仕様2 | 保温仕様3 | 裸管 |
13A以下	 | 0.159 | 0.191 | 0.191 | 0.599 |
20A以下	 | 0.189 | 0.213 | 0.231 | 0.838 |
25A以下	 | 0.218 | 0.270 | 0.270 | 1.077 |
30A以下	 | 0.242 | 0.303 | 0.303 | 1.282 |
40A以下	 | 0.237 | 0.354 | 0.354 | 1.610 |
50A以下	 | 0.257 | 0.388 | 0.388 | 1.832 |
60A以下	 | 0.296 | 0.457 | 0.457 | 2.281 |
75A以下	 | 0.346 | 0.472 | 0.548 | 2.876 |
80A以下	 | 0.387 | 0.532 | 0.621 | 3.359 |
100A以下 | 0.466 | 0.651 | 0.651 | 4.309 |
125A以下 | 0.464 | 0.770 | 0.770 | 5.270 |
125Aより大きい|	0.528|0.774|0.889|6.228|
|=================================


<<<<
==== D.6 日平均給水温度

日平均給水温度は地域区分毎に定められている。

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[\theta_{Win,d}]|日付dにおける日平均給水温度|℃|5.5|
|=================================

日付dにおける日平均給水温度は、次式にて算出する。
ここで、stem:[\theta_{oa,d}] は 日付dにおける日平均外気温度であり、地域区分毎に定められている。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
\theta_{Win,d}= a_{w} \times \theta_{oa,d} + b_{w}
++++++++++++++++++++++++++++++++++++++++++++
====

式中の係数 stem:[a_{w}]、stem:[b_{w}] は下表に示す通り、地域別に定められている。
なお、この算出方法は、住宅事業建築主の判断基準における日平均給水温度の算出法を引用している

.日平均給水温度推定式の係数
[options="header", cols="3,2,2"]
|=================================
|地域区分| 係数 stem:[a_{w}] | 係数 stem:[b_{w}] |
1地域 | 0.664 | 3.466 |
2地域 | 0.664 | 3.466 |
3地域 | 0.605 | 4.515 |
4地域 | 0.605 | 4.515 |
5地域 | 0.866 | 1.665 |
6地域 | 0.852 | 2.473 |
7地域 | 0.922 | 2.097 |
8地域 | 0.692 | 7.167 |
|=================================
