:stem: latexmath

== 6. 昇降機の評価方法

昇降機の一次エネルギー消費量算出ロジックを示す。

=== 6.1 はじめに

==== 6.1.1 用語の定義

===== 6.1.1.1　昇降機
　一定の昇降路、経路その他これに類する部分を介して、動力を用いて人または物を建築物のある階またはある部分から他の階または他の部分へ移動・運搬するための設備。

===== 6.1.1.2　昇降機系統
　一体として制御される昇降機群のことをいう。複数の昇降機で構成される場合もあれば、1台で系統が構成される場合もある。

===== 6.1.1.3　積載質量
　かごに乗り込む利用者及び搭載する荷物などの自重により生ずるかごの定格質量。

===== 6.1.1.4　定格速度
　かごが上昇、下降するときの毎分の定格速度。

===== 6.1.1.5　速度制御方式による補正係数
　消費電力量を求めるための係数。消費電力は制御方式毎にエレベータの積載質量、速度、起動頻度に比例している。これらより各々の制御方式毎に導き出した換算係数。


=== 6.2 昇降機の設計一次エネルギー消費量

昇降機の年間一次エネルギー消費量 stem:[E_{EV}] [MJ/年]を算出する。

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[E_{EV,i}]| 昇降機系統iの年間電力消費量| kWh/年 |6.3|
stem:[N_{EV,i}]| 昇降機系統iに属する昇降機の数 |台 |入力|
stem:[n_{EV}]| 昇降機の系統の総数 |系統 |入力|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{EV}]|昇降機の設計一次エネルギー消費量|	MJ/年||
|=================================

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{EV} = \sum_{r=1}^{n_{EV}} ( (E_{EV,i} × N_{EV,i} ) × f_{prim,e} × 10^{-3}
++++++++++++++++++++++++++++++++++++++++++++
====


=== 6.3 昇降機の年間電力消費量

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[L_{EV,i}]| 昇降機系統iの積載質量 | kg | 入力 |
stem:[V_{EV,i}]| 昇降機系統iの定格速度 | m/min | 入力 |
stem:[C_{EV,i}]| 昇降機系統iの速度制御方式によって定められる係数 | - | 6.4 |
stem:[T_{EV,i}]| 昇降機系統iの年間運転時間 |時間 | 室使用条件|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{EV,i}]|昇降機系統iの年間電力消費量|kWh/年|6.2|
|=================================

昇降機系統iの年間電力消費量 stem:[E_{EV,i}] [kWh/年]は次式により算出される。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{EV,i} = \frac{ L_{EV,i} × V_{EV,i} × C_{EV,i} × T_{EV,i} }{860}
++++++++++++++++++++++++++++++++++++++++++++
====

=== 6.4 速度制御方式に応じて定められる係数

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
 | 昇降機系統iの速度制御方式の種類| - |入力|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[C_{EV},i]|昇降機系統iの速度制御方式によって定められる係数|-|6.3|
|=================================

.制御方式によって定められる係数
[options="header", cols="5,2"]
|=================================
|速度制御方式の種類|係数の値|
可変電圧可変周波数制御方式（電力回生ありかつギアレス巻上機）|	1/50|
可変電圧可変周波数制御方式（電力回生あり）|	1/45|
可変電圧可変周波数制御方式（電力回生なしかつギアレス巻上機）|	1/45|
可変電圧可変周波数制御方式（電力回生なし）|	1/40|
交流帰還制御方式|	1/20|
|=================================

速度制御方式の種類が指定されていない（入力シートの当該欄が空欄である）場合は「交流帰還制御方式」が選択されたものとする。
