:lang: ja
:doctype: book
:toc: left
:toclevels: 4
:toc-title: 第10章 目次
:sectnums!:
:sectnumlevels: 4
:sectlinks:
:linkattrs:
:icons: font
:source-highlighter: coderay
:example-caption: 例
:table-caption: 表
:figure-caption: 図
:docname: = 平成28年省エネルギー基準一次エネルギー消費量算定方法の解説（非住宅建築物）
:stem: latexmath
:xrefstyle: short

= 平成28年 省エネルギー基準 一次エネルギー消費量算定方法の解説（非住宅建築物）

国土交通省 国土技術政策総合研究所、国立研究開発法人 建築研究所

link:./index.html[トップページに戻る]

== 10. 基準一次エネルギー消費量の算定方法

基準一次エネルギー消費量の算定ロジックを示す。 +
基準一次エネルギー消費量 stem:[E_{ST}] [GJ/年] は次式で算出するものとし、小数点第二位を切り上げた数値であるとする。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{ST} = (E_{SAC} + E_{SV} + E_{SL} + E_{SHW} + E_{SEV} + E_{M} ) \times 10^{-3}
++++++++++++++++++++++++++++++++++++++++++++
====

stem:[E_{SAC}]は空気調和設備の基準一次エネルギー消費量であり、その算出方法は10.1で示す。
stem:[E_{SV}]は機械換気設備の基準一次エネルギー消費量であり、その算出方法は10.2で示す。
stem:[E_{SL}]は照明設備の基準一次エネルギー消費量であり、その算出方法は10.3で示す。
stem:[E_{SHW}]は給湯設備の基準一次エネルギー消費量であり、その算出方法は10.4で示す。
stem:[E_{SEV}]は昇降機の基準一次エネルギー消費量であり、その算出方法は10.5で示す。
stem:[E_{M}]はその他一次エネルギー消費量であり、その算出方法は link:./EngineeringReference_chapter09.html[9章] で示す。


なお、国交省平成28年告示265号別表第2の係数及び当該係数の算定根拠については、次の資料を参照のこと。 +

*建築研究所　平成28年省エネルギー基準に準拠したエネルギー消費性能の評価に関する技術情報（非住宅建築物）* +
*４．基準値に関する情報　4.1　一次エネルギー消費量の基準値に関する情報*
https://www.kenken.go.jp/becc/documents/building/Definitions/kaisetsusyo_DefaultSpec_20140602.pdf[https://www.kenken.go.jp/becc/documents/building/Definitions/kaisetsusyo_DefaultSpec_20140602.pdf]


<<<<
=== 10.1 空気調和設備の基準一次エネルギー消費量

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[CLIMATEZONE]| 評価対象建築物の所在地の地域区分 | - | 様式0：⑤省エネ基準地域区分|
stem:[ROOMTYPE_{AC,r}]| 空調計算対象室rの建物用途・室用途 | - | 様式2-1：①建物用途、室用途|
stem:[A_{AC,r}]| 空調計算対象室rの床面積 |m^2^| 様式2-1：①室面積|
stem:[n_{AC}]| 空調計算対象室の数 | - | 様式2-1：①室名 の総入力行数|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{SAC}]|空気調和設備の基準一次エネルギー消費量| MJ/年 ||
|=================================

空気調和設備の基準一次エネルギー消費量 stem:[E_{SAC}] [MJ/年] は、次式で算出する。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{SAC} = \sum_{r=1}^{n_{AC}} (a_{SAC,r} \times A_{r} )
++++++++++++++++++++++++++++++++++++++++++++
====

係数 stem:[a_{SAC,r}] [MJ/（m^2^・年）]は 国交省平成28年告示265号別表第2 で規定されている値であり、床面積あたりの基準一次エネルギー消費量である。
この係数は、空調計算対象室の室用途及び地域区分毎に規定されており、
様式0：⑤省エネ基準地域区分( stem:[CLIMATEZONE]  )及び 空調計算対象室 r の様式2-1：①建物用途、室用途( stem:[ROOMTYPE_{AC,r}] )の情報から、国交省平成28年告示265号 別表第2 より該当する係数 stem:[a_{SAC,r}] を抽出する。

式中のΣは、入力シートに入力された全ての空調計算対象室について積算することを意味しており、具体的には「様式2-1 空調ゾーン入力シート」に入力された全ての室について積算を行う。
床面積 stem:[A_{AC,r}] には、様式2-1：①室面積 に入力された値を使用する。 +

<<<<
=== 10.2 機械換気設備の基準一次エネルギー消費量

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[ROOMTYPE_{V,r}]| 換気計算対象室rの建物用途・室用途 | - | 様式3-1：①建物用途、室用途|
stem:[A_{V,r}]| 換気計算対象室rの床面積 |m^2^| 様式3-1：①室面積|
stem:[n_{V}]| 換気計算対象室の数 | - | 様式3-1：①室名 の総入力行数|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{SV}]|機械換気設備の基準一次エネルギー消費量| MJ/年 ||
|=================================

機械換気設備の基準一次エネルギー消費量 stem:[E_{SV}] [MJ/年] は、次式で算出する。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{SV} = \sum_{r=1}^{n_{V}} (a_{SV,r} \times A_{V,r} )
++++++++++++++++++++++++++++++++++++++++++++
====

係数 stem:[a_{SV,r}] [MJ/（m^2^・年）]は 国交省平成28年告示265号別表第2 で規定されている値であり、床面積あたりの基準一次エネルギー消費量である。
この係数は、換気計算対象室の室用途及び地域区分毎に規定されており、
換気計算対象室 r の様式3-1：①建物用途、室用途( stem:[ROOMTYPE_{V,r}] )の情報から、国交省平成28年告示265号 別表第2 より該当する係数 stem:[a_{SV,r}] を抽出する。

式中のΣは、入力シートに入力された全ての換気計算対象室について積算することを意味しており、具体的には「様式3-1 換気対象室入力シート」に入力された全ての室について積算を行う。
床面積 stem:[A_{V,r}] には、様式3-1：①室面積 に入力された値を使用する。 +

<<<<
=== 10.3 照明設備の基準一次エネルギー消費量

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[ROOMTYPE_{L,r}]| 照明計算対象室rの建物用途・室用途 | - | 様式4：①建物用途、室用途|
stem:[A_{L,r}]| 照明計算対象室rの床面積 |m^2^| 様式4：①室面積|
stem:[n_{L}]| 照明計算対象室の数 | - | 様式4：①室名 の総入力行数|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{SL}]| 照明設備の基準一次エネルギー消費量| MJ/年 ||
|=================================

照明設備の基準一次エネルギー消費量 stem:[E_{SL}] [MJ/年] は、次式で算出する。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{SL} = \sum_{r=1}^{n_{L}} (a_{SL,r} \times A_{L,r} )
++++++++++++++++++++++++++++++++++++++++++++
====

係数 stem:[a_{SL,r}] [MJ/（m^2^・年）]は 国交省平成28年告示265号別表第2 で規定されている値であり、床面積あたりの基準一次エネルギー消費量である。
この係数は、照明計算対象室の室用途及び地域区分毎に規定されており、
照明計算対象室 r の様式4：①建物用途、室用途( stem:[ROOMTYPE_{L,r}] )の情報から、国交省平成28年告示265号 別表第2 より該当する係数 stem:[a_{SL,r}] を抽出する。

式中のΣは、入力シートに入力された全ての照明計算対象室について積算することを意味しており、具体的には「様式4 照明入力シート」に入力された全ての室について積算を行う。
床面積 stem:[A_{L,r}] には、様式4：①室面積 に入力された値を使用する。 +

<<<<
=== 10.4 給湯設備の基準一次エネルギー消費量

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[CLIMATEZONE]| 評価対象建築物の所在地の地域区分 | - | 様式0：⑤省エネ基準地域区分|
stem:[ROOMTYPE_{HW,r}]| 給湯計算対象室rの建物用途・室用途 | - | 様式5-1：①建物用途、室用途|
stem:[A_{HW,r}]| 給湯計算対象室rの床面積 |m^2^| 様式5-1：①室面積|
stem:[n_{HW}]| 給湯計算対象室の数 | - | 様式5-1：①室名 の総入力行数|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{SHW}]| 給湯設備の基準一次エネルギー消費量| MJ/年 ||
|=================================

給湯設備の基準一次エネルギー消費量 stem:[E_{SHW}] [MJ/年] は、次式で算出する。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{SHW} = \sum_{r=1}^{n_{HW}} (a_{SHW,r} \times A_{HW,r} )
++++++++++++++++++++++++++++++++++++++++++++
====

係数 stem:[a_{SHW,r}] [MJ/（m^2^・年）]は 国交省平成28年告示265号別表第2 で規定されている値であり、床面積あたりの基準一次エネルギー消費量である。
この係数は、給湯計算対象室の室用途及び地域区分毎に規定されており、
様式0：⑤省エネ基準地域区分( stem:[CLIMATEZONE] )及び 給湯計算対象室 r の様式5-1：①建物用途、室用途( stem:[ROOMTYPE_{HW,r}] )の情報から、国交省平成28年告示265号 別表第2 より該当する係数 stem:[a_{SHW,r}] を抽出する。

式中のΣは、入力シートに入力された全ての給湯計算対象室について積算することを意味しており、具体的には「様式5-1 給湯対象室入力シート」に入力された全ての室について積算を行う。
床面積 stem:[A_{HW,r}] には、様式5-1：①室面積 に入力された値を使用する。 +

<<<<
=== 10.5 昇降機の基準一次エネルギー消費量

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[ROOMTYPE_{EV,r}]| 昇降機計算対象室rの建物用途・室用途 | - | 様式6：①建物用途、室用途|
stem:[N_{EV,i}]| 昇降機系統iに属する昇降機の数 |台 |様式6：③台数|
stem:[L_{EV,i}]| 昇降機系統iの積載量 | kg | 様式6：④積載量 |
stem:[V_{EV,i}]| 昇降機系統iの定格速度 | m/min | 様式6：⑤速度 |
stem:[M_{EV,i}]| 昇降機系統iの輸送能力係数 | - | 様式6：⑥輸送能力係数 |
stem:[n_{EV}]| 昇降機の系統の総数 |系統 |様式6：②機器名称の総行数|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{SEV}]|昇降機の基準一次エネルギー消費量| MJ/年||
|=================================

昇降機の基準一次エネルギー消費量 stem:[E_{SEV}] [MJ/年] は、次式で算出する。

====
[stem]
++++++++++++++++++++++++++++++++++++++++++++
E_{SEV} = \sum_{i=1}^{n_{EV}} ( \frac{ L_{EV,i} \times V_{EV,i} \times C_{SEV,i} \times T_{EV,i} \times M_{EV,i} }{860} \times N_{EV,i} ) \times f_{prim,e} × 10^{-3}
++++++++++++++++++++++++++++++++++++++++++++
====

式中の stem:[T_{EV,i}] は昇降機系統iの年間運転時間であり、昇降機計算対象室rの建物用途・室用途 stem:[ROOMTYPE_{EV,r}] によって定まる。
なお、昇降機の年間運転時間は、照明設備の年間点灯時間と等しいとする。

係数 stem:[C_{SEV,i}] は基準設定速度制御係数であり 1/40 とする。
この値は、速度制御方式が「可変電圧可変周波数制御方式（電力回生なし）」のときの速度制御係数である。

式中のΣは、入力シートに入力された全ての昇降機計算対象室について積算することを意味しており、具体的には「様式6 昇降機入力シート」に入力された全ての室について積算を行う。

式中の stem:[M_{EV,i}] は昇降機系統iの輸送能力係数である。輸送能力係数とは、標準的な5分間輸送能力と計画された昇降機の5分間輸送能力との比であり、エレベーターのサービス水準が過剰に設定された場合に、基準一次エネルギー消費量を見かけ上小さくなるように補正するための係数である。輸送能力係数の算出には次のルールを適用できるものとする。

* 主たる建物用途が事務所等、ホテル等の場合において、昇降機の台数が2台以下の場合、もしくはバックヤードに設置される場合は、輸送能力係数は1とすることができるものとする。
* 主たる建物用途が事務所等、ホテル等以外の場合は、輸送能力係数は台数に依らず1とすることができるものとする。
* 事務所等、ホテル等において、計画輸送能力が標準輸送能力を超えるときにおいて、（計画台数-1）の台数で標準輸送能力を下回る場合は、輸送能力係数は1とすることができるものとする。
* 主たる建物用途が事務所等であり、当該建築物の階数が4階以下または床面積の合計が4，000㎡以下の場合には、平均運転時間間隔ΔT［秒］を30で除した値を輸送能力係数とすることができるものとする。但し、平均運転時間間隔が30秒以上の場合は輸送能力係数は1とする。

