:lang: ja
:doctype: book
:toc: left
:toclevels: 4
:toc-title: 第3章 目次
:sectnums!:
:sectnumlevels: 4
:sectlinks:
:linkattrs:
:icons: font
:source-highlighter: coderay
:example-caption: 例
:table-caption: 表
:figure-caption: 図
:docname: = 平成28年省エネルギー基準一次エネルギー消費量算定方法の解説（非住宅建築物）
:stem: latexmath
:xrefstyle: short

= 平成28年 省エネルギー基準 一次エネルギー消費量算定方法の解説（非住宅建築物）

国土交通省 国土技術政策総合研究所、国立研究開発法人 建築研究所

link:./index.html[トップページに戻る]

== 3. 機械換気設備の評価方法

機械換気設備の一次エネルギー消費量算出ロジックを示す。

=== 3.1 はじめに

==== 3.1.1 適用範囲

計算の対象とする機械換気設備は次の通りである。

. 主として排熱、除湿、脱臭を目的とした送風機を空気調和設備以外の機械換気設備と定義し、これを計算対象とする。

* 空調対象室に設置された新鮮外気導入のための機械換気設備は、機械換気設備とはせず空気調和設備とする。例えば、パッケージ型空調機等と併用される全熱交換器は、新鮮外気導入のための設備であるため空気調和設備の一部とみなし、空気調和設備の計算対象とする。

* ただし、排熱、除湿、脱臭を主目的とした機械換気設備がある空調対象室(例えばトイレや喫煙室など)については、新鮮外気分は空気調和設備のエネルギー消費量に、排熱などの分は換気エネルギー消費量に計上する。

* 電気室やエレベータ機械室などのように、一般的に換気をするところを冷房する場合については、換気設備とみなし、換気設備の計算対象とする。

. 旧基準では対象外であった単相の送風機、単体の定格出力が 0.2kW 以下の送風機も、定格出力の合計が 5.5kW 未満の送風機も、平成 25 年基準では計算の対象とする。

. 非常用発電機室の換気設備のように、常時運転されない換気設備や、会議室に設置されるタバコの煙を排気するための(給排気バランス上常時運転しない)換気設備などは計算対象外とする。

. 最近、給気を冷却あるいは加熱する場合も増えている厨房については、給気空気を冷却あるいは加熱するためのエネルギーは計算対象外とし、厨房用の給気と排気の送風機動力のみを計算対象とする。

. 駐車場のドライエリアについては省エネルギー手法とみなし、ドライエリアを設けて第三種換気方式とした場合は、排気送風機の動力のみを換気設備の計算対象とする。(基準値は第 一種換気方式を想定して決定されている)

. 換気の一部を自然通風により賄う場合は、その分選定された換気設備の容量が小さくなっていると想定されるため、何も補正を行わず、選定された機器の消費電力を用いて計算する。(基準値は自然通風なしを想定した消費電力であるため、これと設計値との差が自然通風による省エネルギー量である) 

. 空気の移動を促進するために給排気設備とは別に空気循環用送風機設備を設ける時は、その設備が設置される室が空調対象室であれば、空気循環用送風機設備は空気調和設備として空調設備の送風機動力として計上する。非空調室であれば、空気循環用送風機設備は機械換気設備として機械換気設備の送風機動力として計上する。


次の機械換気設備は対象とはしない。  

* 実験室などにおける局所換気設備(スクラバー、ドラフトチャンバー等)

==== 3.1.2 用語の定義

. *機械換気設備* +
　送風機の機械力を使って給排気をし、主として排熱、除湿、脱臭を目的とした換気を行うための設備のこと。

. *機械換気設備の消費電力* +
　機械換気設備が当該建物に設置され、計画した風量で連続運転しているときの電動機及び換気設備に含まれる補機類の消費電力の合計値。

. *送風機の電動機出力* +
　電動機によって、電気エネルギーから変換された送風機を稼動させるための機械的な回転エネルギー。

. *電動機効率* +
　電動機に供給される電力（入力電力）に対する電動機出力の比。

. *負荷率* +
　実際にかかる冷房負荷を空調機またはパッケージユニットの必要冷房能力で除した値。換気代替空調機の仮想的な消費電力を求める際に用いる。

. *制御の方式に応じて定められる係数* +
　機器の運転効率化のための各種制御を導入した場合のエネルギー削減効果を見込むための係数。

==== 3.1.3 共通の定数

本章で使用する共通の定数を以下に示す。

.共通の定数
[options="header", cols="2,5,2,1"]
|=================================
|定数名|説明|単位|値|
stem:[\eta_{m}]|電動機効率|-|0.75|
|=================================


=== 3.2 機械換気設備の年間一次エネルギー消費量

機械換気設備の年間一次エネルギー消費量 stem:[E_{V}] [MJ/年]を算出する。

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[E_{V,i}]|機械換気設備iの年間電力消費量|kWh|3.3.1、3.3.2|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{V}]|機械換気設備の設計一次エネルギー消費量|MJ/年|-|
|=================================

====
[stem]
++++
E_{V} = \sum_{i=1}E_{V,i} \times f_{prim,e} \times 10^{-3}
++++
====

=== 3.3 機械換気設備の年間電力消費量

==== 3.3.1 換気送風機

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[P_{V,motor,rated,i}]|機械換気設備iの電動機定格出力|kW|様式3-1：③電動機定格出力|
stem:[f_{V,ctrl,i}]|機械換気設備iの制御方法に応じて定められる係数|-|3.4|
stem:[T_{V,i,r}]|機械換気設備iが接続する室rの年間運転時間|時間|B.2|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{V,i}]|機械換気設備iの年間電力消費量|kWh|3.2|
|=================================

====
[stem]
++++
E_{V,i} = \frac{ P_{V,motor,rated,i} \times f_{V,ctrl,i} }{ \eta_{m} } \times \max_{r}( T_{V,i,r} )
++++
====

また、
stem:[\eta_{m}] は電動機効率である。

==== 3.3.2 換気代替空調機

電気室やエレベータ機械室などのように、一般的に換気をするところを空調機やパッケージユニットを利用して冷房を行う場合については、次式により年間電力消費量 stem:[E_{V,i}] [kWh]を求める。

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[RoomType_{V_{AC},i}]|換気代替空調機iによる換気対象室の用途|-|様式3-3：②換気対象室の用途|
stem:[q_{V_{AC},c,i}]|換気代替空調機iの必要冷却能力|kW|様式3-3：③必要冷却能力|
stem:[\eta_{V_{AC},sys,prime,i}]|換気代替空調機iの熱源システムCOP（一次エネルギー換算）|-|様式3-4：④熱源効率（一次換算）|
stem:[P_{V_{AC},pump,rated,i}]|換気代替空調機iのポンプの定格電動機出力|kW|様式3-3：⑤ポンプ定格出力|
stem:[P_{V_{AC},motor,rated,i}]|換気代替空調機iの送風機の電動機定格出力|kW|様式3-3：⑧電動機定格出力|

stem:[Type_{V,i,j}]|換気代替空調機iと併用される送風機jの種類|-|様式3-3：⑥送風機の種類|
stem:[V_{V,design,i,j}]|換気代替空調機iと併用される送風機jの設計風量|m^3^/h|様式3-3：⑦設計風量|
stem:[P_{V,motor,rated,i,j}]|換気代替空調機iと併用される換気送風機jの定格電動機出力|kW|様式3-3：⑧電動機定格出力|

stem:[f_{V_{AC},ctrl,i}]|換気代替空調機iの制御方法に応じて定められる係数|-|3.4|
stem:[f_{V,ctrl,i,j}]|換気代替空調機iと併用される換気送風機jに採用される制御方式に応じて定められる係数|-|3.4|

stem:[\theta_{oa,m}]|中間期平均外気温度|℃|B.1|
stem:[T_{V,i,r}]|換気代替空調機iが接続する室rの年間運転時間|時間|B.2|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[E_{V,i}]|機械換気設備iの年間電力消費量|kWh|3.2|
|=================================

====
[stem]
++++
E_{V,i} = ( P_{V_{AC},i} + P_{V_{AC},motor,i} + P'_{V,motor,i} ) \times \max_{r} ( T_{V,i,r} )
++++

[stem]
++++
P_{V_{AC},i} = (\frac{ q_{V_{AC},c,i} \times R_{V_{AC},load,i} }{ 2.71 \times \eta_{V_{AC},sys,prime,i} } +  \frac{ P_{V_{AC},pump,rated,i} }{ \eta_{m} } ) \times R_{V_{AC},operate,i}
++++

[stem]
++++
P_{V_{AC},motor,i} = \sum_{j=1} ( \frac{ P_{V_{AC},motor,rated,i,j} \times f_{V_{AC},ctrl,i,j} }{ \eta_{m} } ) \times R_{V_{AC},operate,i}
++++

[stem]
++++
P'_{V,motor,i} = \sum_{j=1} ( \frac{ P_{V,motor,rated,i,j} \times f_{V,ctrl,i,j} }{ \eta_{m} } \times R_{V,operate,i,j} )
++++
====

また、
stem:[\eta_{m}] は電動機効率である。


換気代替空調機iの年間平均負荷率 stem:[R_{V_{AC},load,i}]　は下表より求める。

.換気対象室の用途に応じた換気代替空調機の年間平均負荷率
// [options="header", cols="2,2"]
[options="header", cols="2*"]
|===
|換気対象室の用途 stem:[RoomType_{V_{AC},i}]
|年間平均負荷率 stem:[R_{V_{AC},load,i}]

|電気室
|0.6

|機械室
|0.6

|エレベータ機械室
|0.3

|その他
|1.00
|===


換気代替空調機iの稼働率 stem:[R_{V_{AC},operate,i}] 、換気代替空調機iと併用される送風機の稼働率 stem:[R_{V,operate,i,j}] は下表より求める。

.換気代替空調機および併用する送風機の年間稼働率
[options="header", cols="5,2,2"]
|===
|適用条件
|換気代替空調機の年間稼働率 stem:[R_{V_{AC},operate,i}]
|併用する送風機の年間稼働率 stem:[R_{V,operate,i,j}]

|「換気代替空調機iと併用される送風機jの外気導入量」が「外気冷房に必要な外気導入量」より大きい場合
|0.35
|0.65

|上記以外
|1.00
|1.00
|===

ここで、「換気代替空調機iと併用される送風機jの外気導入量」は下表のように求める。

.換気代替空調機iと併用される送風機の外気導入量
[options="header", cols="4,3"]
|===
|適用条件
|換気代替空調機iと併用される送風機jの外気導入量

|送風機の種類が「給気」である送風機が1台以上ある場合
|送風機の種類が「給気」である送風機の「設計風量」の合計値

|送風機の種類が「給気」が１台もなく、送風機の種類が「排気」である送風機が１台以上ある場合
|送風機の種類が「排気」である送風機の「設計風量」の合計値

|上記以外
|0
|===

外気冷房に必要な外気導入量 stem:[V_{AC,oacool,i}] は次式により求める。

====
[stem]
++++
V_{AC,oacool,i} =  \frac{ 1000 \times q_{AC,c,i} }{ 0.33 \times ( 40 - \theta_{oa,m} ) }
++++
====

なお、換気代替空調機iの必要冷却能力の決定方法について、以下のルールを設ける。

** 電気室等において、設置される機器の能力に余裕を見込んでいる場合は、必要とされる能力を算出し、この値を入力してもよい。
例えば故障時の対応として必要冷房能力 100%の機器が2台設置されている場合は、1台分のみ能力を入力してもよい。
ただし、この必要能力の算出根拠は別途提出する必要がある。

** エレベータ機械室については、昇降機メーカー等が算出した設計発熱量を用いても良い。
ただし、算出根拠は別途提出する必要がある。



=== 3.4 制御の方式に応じて定められる係数

機械換気設備の運転効率化のための各種措置について、次のように3つのカテゴリに分類し、それぞれ講じた措置の種類に応じて、係数 stem:[f_{V,ctrl,motor,i}] 、stem:[f_{V,ctrl,inverter,i}] 、stem:[f_{V,ctrl,type,i}] の値を定める。同じカテゴリの中から重複して係数を採用することはできず、各カテゴリの中から何れか1つを選択して値を決定する。

.入力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照先|
stem:[f_{V,ctrl,motor,i}]|高効率電動機の有無によって決まる係数|-|3.4.1|
stem:[f_{V,ctrl,inverter,i}]|インバータの有無によって決まる係数|-|3.4.2|
stem:[f_{V,ctrl,type,i}]|送風量制御の種類によって決まる係数|-|3.4.3|
|=================================

.出力
[options="header", cols="2,5,2,1"]
|=================================
|変数名|説明|単位|参照元|
stem:[f_{V,ctrl,i}]|機械換気設備iの制御方法に応じて定められる係数|-|3.3.1, 3.3.2|
|=================================

エネルギー消費量計算に用いる係数 は次式で求める。

====
[stem]
++++
f_{V,ctrl,i} = f_{V,ctrl,motor,i} \times f_{V,ctrl,inverter,i} \times f_{V,ctrl,type,i}
++++
====

==== 3.4.1 高効率電動機の採用

下表に示すとおり、高効率電動機を採用していない場合は「無」の係数を、高効率電動機を採用している場合は「有」の係数を適用する。 + 
選択肢が指定されていない（入力シートの当該欄が空欄である）場合は「無」が選択されたものとする。

.高効率電動機の採用による係数
[options="header", cols="1,6,2"]
|===
|選択肢
|適用
|高効率電動機の有無によって決まる係数 stem:[f_{V,ctrl,motor,i}]

|有
|JIS C 4212に準拠した低圧三相かご形誘導電動機が採用されている場合
|0.95

|無
|上記以外
|1.00
|===


電動機効率 は 0.75 を想定しているので、高効率電動機とは0.79（ stem:[= \frac{0.75}{0.95}] ）程度の効率を想定していることになる。


==== 3.4.2 インバータの採用

下表に示す通り、インバータを採用していない場合は「無」の係数を、インバータを採用している場合は「有」の係数を適用する。 + 
選択肢が指定されていない（入力シートの当該欄が空欄である）場合は「無」が選択されたものとする。


.インバータの採用による係数
[options="header", cols="1,6,2"]
|===
|選択肢
|適用
|インバータの有無によって決まる係数 stem:[f_{V,ctrl,inverter,i}]

|有|ンバータが設置されている場合。ただし、自動制御が行われておらず固定周波数で運用する場合も含まれる
|0.60

|無
|上記以外
|1.00
|===


なお、インバータによる回転数の自動制御が行われておらずに固定周波数で運用する場合も「有」を適用して良い。


==== 3.4.3 送風量制御の採用

下表に示す通り、CO濃度制御やCO~2~濃度制御を採用している場合は「CO・CO~2~濃度制御」の係数を、
室内温度により送風機制御を行っている場合は「温度制御」の係数を、これらの制御を行っていない場合は「無」の係数を適用する。 + 
選択肢が指定されていない（入力シートの当該欄が空欄である）場合は「無」が選択されたものとする。

.送風機制御の採用による係数
[options="header", cols="2,5,2"]
|===
|選択肢
|適用
|送風量制御の種類によって決まる係数 stem:[f_{V,ctrl,type,i}]

|CO・CO~2~濃度制御
|駐車場などにおいてCO濃度やCO~2~濃度により送風機制御を行っている場合
|0.60

|温度制御
|電気室などにおいて室内温度により送風機制御を行っている場合
|0.70

|無
|上記以外
|1.00
|===



=== 附属書B（機械換気）

==== B.1 中間期平均外気温度

中間期平均外気温度 stem:[\theta_{oa,m}] は地域区分毎に下表で定められる。

.入力
[options="header", cols="2,5,2,2"]
|=================================
|変数名|説明|単位|参照先|
stem:[ClimateZone]|評価対象建築物の所在地の地域区分|-|様式0：⑤省エネ基準地域区分|
|=================================

.出力
[options="header", cols="2,5,2,2"]
|=================================
|変数名|説明|単位|参照先|
stem:[\theta_{oa,m}]|中間期平均外気温度|℃|3.3.2|
|=================================

.中間期平均外気温
[options="header", cols="2,2"]
|===
|地域|中間期平均外気温度 stem:[\theta_{oa,m}]
|1地域|22.7
|2地域|22.5
|3地域|24.7
|4地域|27.1
|5地域|26.7
|6地域|27.5
|7地域|25.8
|8地域|26.2
|===


==== B.2 年間運転時間

機械換気設備の年間運転時間は、室用語毎に標準室使用条件によって定められている。
標準室使用条件は次のファイルにて規定されており、対象室の建物用途・室用途に応じて該当するスケジュールを抽出する。

* 建物用途・室用途の一覧： link:https://github.com/WEBPRO-NR/BESJP_Webpro_RouteB/blob/dev/database/ROOM_NAME.csv[ROOM_NAME.csv]
* 運転時間の参照値： link:https://github.com/WEBPRO-NR/BESJP_Webpro_RouteB/blob/dev/database/ROOM_SPEC_H28.csv[ROOM_SPEC_H28.csv]


.入力
[options="header", cols="2,5,2,2"]
|=================================
|変数名|説明|単位|参照先|
stem:[BuildingType]|建物用途|-|様式3-1：①建物用途・室用途|
stem:[RoomType_{i}]|室iの室用途|-|様式3-1：①建物用途・室用途|
|=================================

.出力
[options="header", cols="2,5,2,2"]
|=================================
|変数名|説明|単位|参照先|
stem:[T_{V,i,r}]|室rに接続する機械換気設備iの年間運転時間|時間|3.3.1、3.3.2|
|=================================

* データベースの検索キーを取得する。

建物用途 stem:[BuildingType] と室用途 stem:[RoomType_i] を用いて、ROOM_NAME.csvより検索キーを取得する。
====
例）建物用途が「事務所等」で室用途が「事務室」の場合、検索キーは「O-1」となる。
====

* 年間運転時間を取得する。

検索キーを用いて、ROOM_SPEC.csvより「年間換気時間」の列の該当する値を年間運転時間として取得する。
====
例）検索キーが「O-1」の場合、年間運転時間は「0」となる。
====
