:lang: ja
:doctype: book
:sectnums!:
:sectnumlevels: 4
:sectlinks:
:linkattrs:
:icons: font
:source-highlighter: coderay
:example-caption: 例
:table-caption: 表
:figure-caption: 図
:docname: = 平成28年省エネルギー基準一次エネルギー消費量算定方法の解説（非住宅建築物）
:stem: latexmath
:xrefstyle: short

= 平成28年省エネルギー基準 一次エネルギー消費量算定方法の解説（非住宅建築物）

国土交通省 国土技術政策総合研究所、国立研究開発法人 建築研究所

[NOTE]
====
* 国土交通省国土技術政策総合研究所、国立研究開発法人建築研究所は、プログラム及び資料等により、使用者が直接間接に蒙ったいかなる損害に対しても、何らの保証責任及び賠償責任を負うものではありません。 使用者の責任のもと、プログラムの使用、結果の利用を行ってください。
====

建築物省エネ法に基づく省エネルギー基準への適合性を判定するプログラムの解説書です。設計一次エネルギー消費量の計算方法を解説します。
プログラムはlink:http://building.app.lowenergy.jp/[こちら]で公開しています。


=== 第１章　はじめに

本資料で使用する共通の定数を次に示す。

.共通の定数
[options="header", cols="2,6,2,2"]
|=================================
|定数名| 説明| 値| 単位|
stem:[f_{prim,e}]|電気の量1キロワット時を熱量に換算する係数| 9760|kJ/kWh|
stem:[C_{a}]|	乾き空気の定圧比熱|  1.006|	kJ ⁄ (kg・K)|
stem:[C_{wv}]|	水蒸気の定圧比熱 | 1.805|	kJ ⁄ (kg・K)|
stem:[C_{w}]|	水の定圧比熱 | 4.186|	kJ ⁄ (kg・K)|
stem:[L_{w}]|	水の蒸発潜熱|  2502|	kJ ⁄ (kg・K)|
stem:[\rho_{w}]|	水の密度（大気圧、7度）| 1000 | kg⁄stem:[m^{3}]|
stem:[\alpha_{o}]| 室外側総合熱伝達率| 1/0.04	|W/(stem:[m^{2}]・K)|
stem:[\alpha_{i}]|	室内側総合熱伝達率| 1/0.11|	W/(stem:[m^{2}]・K)|
stem:[f_{fan,heat}]| ファンの発熱比率| 0.84| -|
stem:[f_{pump,heat}]| ポンプの発熱比率| 0.84| -|
stem:[f_{ref,ts,loss}]| 蓄熱槽の熱損失係数| 0.03|-|
|=================================


=== 第２章　link:./EngineeringReference_chapter02.html[空気調和設備の評価方法]

=== 第３章　link:./EngineeringReference_chapter03.html[機械換気設備の評価方法]

=== 第４章　link:./EngineeringReference_chapter04.html[照明設備の評価方法]

=== 第５章　link:./EngineeringReference_chapter05.html[給湯設備の評価方法]

=== 第６章　link:./EngineeringReference_chapter06.html[昇降機の評価方法]


==== 参考資料

* 建築研究資料第191号: 業務用コージェネレーション設備の性能評価手法の高度化に関する研究、H31.04
* 建築研究資料第190号: 各種空調設備システムの潜熱負荷処理メカニズムを踏まえたエネルギー消費量評価法に関する検討、H31.04
* 建築研究資料第188号: 太陽光発電設備の年間発電量の推計方法に関する調査、H30.01
* 建築研究資料第187号: 建築物の設備・機器のエネルギー効率に関する既存試験方法の調査、H29.09
* 国総研資料第974号、建築研究資料第183号: 平成28年省エネルギー基準（平成28年1月公布）関係技術資料 モデル建物法入力支援ツール解説、H29.06
* 国総研資料第973号	建築研究資料第182号: 平成28年省エネルギー基準（平成28年1月公布）関係技術資料　エネルギー消費計算プログラム（非住宅版）解説、H29.06
* 建築研究資料第177号: 業務用空調・給湯システムの制御による省エネルギー効果の実証的評価、H28.11
* 建築研究資料第176号: 業務用建築物のエネルギー消費量評価手法に関する基礎的調査、H28.11
* 国総研資料第765号	建築研究資料第152号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 モデル建物法による非住宅建築物の外皮性能及び一次エネルギー消費量評価プログラム解説、H25.11
* 国総研資料第764号	建築研究資料第151号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 主要室入力法による非住宅建築物の一次エネルギー消費量算定プログラム解説、H25.11
* 国総研資料第763号	建築研究資料第150号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 非住宅建築物の外皮性能評価プログラム解説、H25.11
* 国総研資料第762号	建築研究資料第149号: 平成25年省エネルギー基準(平成25年9月公布)等関係技術資料 一次エネルギー消費量算定プログラム解説(非住宅建築物編)、H25.11
* 国総研資料第702号	建築研究資料第140号: 低炭素建築物認定基準(平成24年12月公布)等関係技術資料 一次エネルギー消費量算定プログラム解説(建築物編)、H24.12


[NOTE]
====
* この文章は、asciidocで書かれています。詳細はlink:https://asciidoctor.org/docs/user-manual/[こちら]。
** 日本語版は link:https://takumon.github.io/asciidoc-syntax-quick-reference-japanese-translation/[こちら]
* 数式入力（latex）についてはlink:http://www.latex-cmd.com/[こちら]。
* 数式記号の入力はlink:https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols[こちら]
====




